// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATEOT6lCGqcqS1wLnGsI92E0RBhUyNPK8',
    appId: '1:494002299863:web:c184c44f41841e447ca192',
    messagingSenderId: '494002299863',
    projectId: 'mujbites-58abc',
    authDomain: 'mujbites-58abc.firebaseapp.com',
    storageBucket: 'mujbites-58abc.firebasestorage.app',
    measurementId: 'G-C4M6X7F7P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZHyqfalEJSIZ8vflthLs9dMg9UvWPGo',
    appId: '1:494002299863:android:3d7394ca402ea0f47ca192',
    messagingSenderId: '494002299863',
    projectId: 'mujbites-58abc',
    storageBucket: 'mujbites-58abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf_9aB1TJX5ufMKXCcvQZNyFHqiEpL7Gg',
    appId: '1:494002299863:ios:23346ef1960134b97ca192',
    messagingSenderId: '494002299863',
    projectId: 'mujbites-58abc',
    storageBucket: 'mujbites-58abc.firebasestorage.app',
    iosBundleId: 'com.satwik.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf_9aB1TJX5ufMKXCcvQZNyFHqiEpL7Gg',
    appId: '1:494002299863:ios:bf97dc831fdec2927ca192',
    messagingSenderId: '494002299863',
    projectId: 'mujbites-58abc',
    storageBucket: 'mujbites-58abc.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATEOT6lCGqcqS1wLnGsI92E0RBhUyNPK8',
    appId: '1:494002299863:web:acb0872459c80c1e7ca192',
    messagingSenderId: '494002299863',
    projectId: 'mujbites-58abc',
    authDomain: 'mujbites-58abc.firebaseapp.com',
    storageBucket: 'mujbites-58abc.firebasestorage.app',
    measurementId: 'G-XJ3JELDSHM',
  );
}
